### ISSUE TITLE
Error: The domain: www.google.com does not exist or is not accessible from the host you are compiling on

### ISSUE THREAD

**Issue by 1483769879** [Tylous/Limelighter#11]
Error: The domain: www.google.com does not exist or is not accessible from the host you are compiling on
<img width="776" alt="image" src="https://user-images.githubusercontent.com/45674906/223915820-a2e7a72c-6480-4b3e-995b-a839d0d3f015.png">

**Comment by Tylous** [comment]
Right, does that host have internet access or can it reach out to google.com?
