### ISSUE TITLE
Simple Question

### ISSUE THREAD

**Issue by mantoheLE** [Tylous/Limelighter#5]
Dear Tylous
"cmd.Run() failed with exec: "osslsigncode": executable file not found in %PATH%"

do you have any idea of why am i getting this error? Thanks in advance

**Comment by Tylous** [comment]
My best guess is because your using windows. Try OS X or Ubuntu

**Comment by lazyDreamerBoy** [comment]
because you dident install osslsigncode package

**Comment by Tylous** [comment]
Are you still having this issue? I am not 100% osslsigncode works well on windows so it might be something to use on linux and osx.

**Comment by psauxx** [comment]
as we can see 
https://github.com/antoinevg/osslsigncode/blob/master/configure
mainly use shell commands / " sh / bash  " a osx os or linux will fix this issue since this lib was made for linux or osx system :lady_beetle:
