### ISSUE TITLE
#1 SMP Debian 5.15.15-2kali1 (2022-01-31) hava error

### ISSUE THREAD

**Issue by closeto** [Tylous/Limelighter#9]
└─# ./Limelighter -I 1.exe -O chrome.exe -Domain google.com

        .____    .__               .____    .__       .__     __                
        |    |   |__| _____   ____ |    |   |__| ____ |  |___/  |_  ___________ 
        |    |   |  |/     \_/ __ \|    |   |  |/ ___\|  |  \   __\/ __ \_  __ \
        |    |___|  |  Y Y  \  ___/|    |___|  / /_/  >   Y  \  | \  ___/|  | \/
        |_______ \__|__|_|  /\___  >_______ \__\___  /|___|  /__|  \___  >__|   
                \/        \/     \/        \/ /_____/      \/          \/         
                                                        @Tyl0us

[*] A Tool for Code Signing... Real and fake
[*] Signing 2.exe with a fake cert
2022/12/01 02:02:58 cmd.Run() failed with exit status 255

**Comment by Tylous** [comment]
it says signing 2.exe but that's not the name in your command line arguments so that's weird. My only other thought is that you don't have Internet access to reach that domain. I would ask for more details, please.

**Comment by Tylous** [comment]
Update: This appears to be an issue with osslsigncode. The fix is to have osslsigncode 2.5  with OpenSSL 3.0.7. Brew and the other main repos currently do not have this version ready for everyone.
